### ISSUE TITLE
[Question]Local variables have the same name

### ISSUE THREAD

**Issue by xubury** [Krozark/SFML-book#12]
In the following code there're two `i`. 
https://github.com/Krozark/SFML-book/blob/ab1f5277947cc7b36b65835c6ba8fc5ce8393811/extlibs/SFML-utils/include/SFML-utils/es/EntityManager.tpl#L125-L133
I am little confused here. I think what you mean is something like this?
```
for(std::size_t i=0;i<comp_size;++i) 
{ 
       if(_componentsEntities[i] != nullptr) 
       { 
              for(size_t j = 0;i<_entitiesIndex.size();++j) 
                     _componentsEntities[i]->erase<VComponent<ENTITY>>(j); 
              delete _componentsEntities[i]; 
      } 
}
```
Also, dosen't the second `i` shadow the first `i`.  So is it a bug?

**Comment by Krozark** [comment]
Yes, it's a bug. The second "i" should be something else , like "j" as you suggest.
