### ISSUE TITLE
Wrong usage of std::memcpy

### ISSUE THREAD

**Issue by eXpl0it3r** [Krozark/SFML-book#3]
As pointed out by @zsbzsb in issue #2 and by me in the partial "review" of the book, the usage of `std::memcpy` is wrong, dangerous and unnecessary.

Your explenation from the book reads as following:

> Because the `sf::Event`class doesn't implement the copy-operator/constructor, we use the `std::memcopy()` function from the C string module. This allows us to copy the entire content of a `sf::Event` simply by knowing its size, ...

It's true that `sf::Event` doesn't implement a copy-constructor or assignment operator, but it doesn't matter because as the C++11 standard says in §12.8.7:

> If the class deﬁnition does not explicitly declare a copy constructor, one is declared implicitly. If the class deﬁnition declares a move constructor or move assignment operator, the implicitly declared copy constructor is deﬁned as deleted; otherwise, it is deﬁned as defaulted (8.4). The latter case is deprecated if the class has a user-declared copy assignment operator or a user-declared destructor.

While `sf::Event` doesn't implement a copy-constructor the compiler will implicitly generate one and thus the class is very well copyable.

Besides that you should really learn more about functions such as `std::memcpy`. They are seen as dangerous not just because it's C, but because it deals with raw memory data and if you don't watch out, your stuff can end up crashing badly. See the [Code Police](http://www.codepolice.org/c/memcpy.html) article for more information on the topic, especially regarding:

> Some types of class, structure and **union** in C++ **cannot** be safely copied using `memcpy`.

For your code you can remove the copy-constructor and assignment operator completely, since the compiler will generate them automatically. And for the constructor you can simply write:

``` cpp
     Action::Action(const sf::Mouse::Button& button,int type) : _type(type), 
    {
        _event.type = sf::Event::EventType::MouseButtonPressed;
        _event.mouseButton = button;
    }
```

**Comment by Krozark** [comment]
Thank's to pointing me this.
I will make the necessary, and update the code/book as soon as possible.
