### ISSUE TITLE
Debug Assertion Failed

### ISSUE THREAD

**Issue by Chiranjivee** [Krozark/SFML-book#4]
I was following your book and got stuck at chapter 3 Asteroid Game.

In the file World.cpp when you are merging the lists enitity and entity_temp.
As the entities, are not ordered we cannot use merge function .

```
    _entities.merge(_entitiesTemp);
```

But if we use this after shooting the meteors the application crashes.

**Comment by Krozark** [comment]
That's a good point.

I'll fix this as soon as possible. Notice that there is no duplication between the two list. So we can use std::list::splice instead of std::list::merge, as the don't have to be sorted.

I'll check this, and push the fix once it'll be tested.
